/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,jsx,ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-surface-variant': '#d1c5b4',
        'tertiary-fixed-dim': '#c8c6c5',
        'surface-container-lowest': '#0d0e10',
        'surface': '#121315',
        'surface-container-high': '#292a2c',
        'surface-dim': '#121315',
        'surface-tint': '#e9c176',
        'primary-container': '#c5a059',
        'on-primary': '#412d00',
        'outline': '#9a8f80',
        'amber-glow': '#FFB800',
        'surface-container': '#1f2022',
        'primary-fixed-dim': '#e9c176',
        'secondary-container': '#ff6a00',
        'border-highlight': 'rgba(255, 255, 255, 0.15)',
        'surface-bright': '#38393b',
        'primary-fixed': '#ffdea5',
        'outline-variant': '#4e4639',
        'background': '#121315',
        'on-surface': '#e3e2e5',
        'secondary': '#ffb694',
        'primary': '#e9c176',
        'inverse-primary': '#775a19',
        'surface-variant': '#343537',
        'surface-glass': 'rgba(30, 30, 30, 0.6)',
        'surface-container-highest': '#343537',
        'surface-container-low': '#1b1c1e',
        'obsidian-deep': '#080808',
        'on-primary-container': '#4e3700',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'section-gap': '120px',
        'margin-mobile': '20px',
        'margin-desktop': '64px',
        'container-max': '1440px',
        'gutter': '24px',
      },
      fontFamily: {
        headline: ['Oswald', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        body: ['Geist', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
